import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {categories,canPublish,emptyBrief,taskScore,type Brief} from '@/lib/readiness';
import {clarify} from '@/lib/assistant';
export const dynamic='force-dynamic';
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
function fail(status:number,message:string):never{throw new HttpError(status,message)}
function database(){if(!env.DB)fail(503,'Хранилище временно недоступно. Попробуйте позже.');return env.DB}
function response(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function str(v:unknown,min=0,max=5000){if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,'Проверьте заполнение полей и длину текста.');return v.trim()}
function safeLink(v:unknown){const s=str(v??'',0,1000);if(s){try{const u=new URL(s);if(!['http:','https:'].includes(u.protocol))throw Error()}catch{fail(400,'Ссылка должна начинаться с https:// или http://.')}}return s}
async function handle(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof HttpError)return response({error:e.message},e.status);console.error('platform',e);return response({error:'Не удалось сохранить или загрузить данные. Введённый текст остался в форме. Попробуйте ещё раз.'},503)}}
export async function GET(){return handle(async()=>{const db=database(),user=await getChatGPTUser(),uid=user?.userId??'';
const profile=user?await db.prepare('SELECT p.*,(SELECT COALESCE(SUM(points),0) FROM proposals WHERE owner=p.id) points FROM profiles p WHERE id=?').bind(uid).first():null;
const tasks=await db.prepare(`SELECT t.*,p.name company,(SELECT COUNT(*) FROM proposals r WHERE r.task=t.id) proposal_count FROM tasks t JOIN profiles p ON p.id=t.owner WHERE t.status!='draft' OR t.owner=? ORDER BY t.created DESC`).bind(uid).all();
const proposals=user?await db.prepare(`SELECT r.*,p.name team,p.university,p.skills,t.title task_title FROM proposals r JOIN profiles p ON p.id=r.owner JOIN tasks t ON t.id=r.task WHERE r.owner=? OR t.owner=? ORDER BY r.created DESC`).bind(uid,uid).all():{results:[]};
const demo=env.APP_DEMO==='true';const personas=demo?(await db.prepare('SELECT id,name,role FROM profiles WHERE id LIKE ? ORDER BY role,name').bind('demo-%').all()).results:[];
return response({user:user?{id:uid,name:user.displayName}:null,profile,tasks:tasks.results.sort((a,b)=>taskScore(b as any)-taskScore(a as any)),proposals:proposals.results,demo,personas})})}
export async function POST(request:Request){return handle(async()=>{if(request.headers.get('origin')!==new URL(request.url).origin)fail(403,'Недопустимый источник запроса.');const user=await getChatGPTUser();if(!user)fail(401,'Войдите, чтобы продолжить.');const raw=await request.text();if(raw.length>80000)fail(413,'Слишком большой запрос.');let b:any;try{b=JSON.parse(raw)}catch{fail(400,'Некорректный запрос.')}if(!b||typeof b!=='object')fail(400,'Некорректный запрос.');const db=database(),uid=user.userId;const profile:any=await db.prepare('SELECT * FROM profiles WHERE id=?').bind(uid).first();
if(b.action==='profile'){if(profile)fail(409,'Профиль уже создан.');if(!['business','team'].includes(b.role))fail(400,'Выберите роль.');await db.prepare('INSERT INTO profiles(id,role,name,university,skills,interests,technologies) VALUES(?,?,?,?,?,?,?)').bind(uid,b.role,str(b.name,2,120),str(b.university??'',b.role==='team'?2:0,160),str(b.skills??'',b.role==='team'?3:0,500),str(b.interests??'',0,500),str(b.technologies??'',0,500)).run();return response({ok:true})}
if(!profile)fail(403,'Сначала заполните профиль.');
if(b.action==='clarify'){if(profile.role!=='business')fail(403,'Конструктор доступен бизнесу.');const fields:any={};for(const k of Object.keys(emptyBrief))fields[k]=str(b.fields?.[k]??'',0,5000);fields.category=categories.includes(fields.category)?fields.category:'Разработка';return response(clarify(str(b.description,3,5000),fields))}
if(b.action==='saveTask'){if(profile.role!=='business')fail(403,'Создавать задачи может представитель бизнеса.');const brief:any={};for(const k of Object.keys(emptyBrief))brief[k]=str(b[k]??'',k==='title'?3:0,k==='title'?160:5000);if(!categories.includes(brief.category))fail(400,'Выберите направление.');if(b.publish!==undefined&&typeof b.publish!=='boolean')fail(400,'Некорректный статус.');const id=b.id?str(b.id,1,80):crypto.randomUUID();let old:any=null;if(b.id){old=await db.prepare('SELECT * FROM tasks WHERE id=? AND owner=?').bind(id,uid).first();if(!old)fail(404,'Задача не найдена.');if(old.status==='closed')fail(409,'Выбор уже завершён. Редактирование закрыто.');}
const publish=b.publish||old?.status==='published';if(publish&&(!canPublish(brief)||b.confirmed!==true))fail(400,'Заполните название и описание, проверьте дату и подтвердите карточку. Минимального рейтинга для публикации нет.');
const confirmed=b.confirmed===true?1:0,status=publish?'published':'draft';const keys=Object.keys(emptyBrief);
if(old){const result=await db.prepare('UPDATE tasks SET '+keys.map(k=>k+'=?').join(',')+',confirmed=?,status=? WHERE id=? AND owner=? AND status!=?').bind(...keys.map(k=>brief[k]),confirmed,status,id,uid,'closed').run();if(!result.meta.changes)fail(409,'Задача уже изменена. Обновите страницу.')}else{await db.prepare('INSERT INTO tasks(id,owner,'+keys.join(',')+',confirmed,status,created) VALUES('+Array(keys.length+5).fill('?').join(',')+')').bind(id,uid,...keys.map(k=>brief[k]),confirmed,status,new Date().toISOString()).run()}return response({ok:true,id,score:confirmed?taskScore({...brief,confirmed}):0})}
if(b.action==='propose'){if(profile.role!=='team')fail(403,'Предложения отправляют студенческие команды.');const taskId=str(b.task,1,80),id=str(b.clientId,10,80);const task:any=await db.prepare('SELECT * FROM tasks WHERE id=?').bind(taskId).first();if(!task||task.status!=='published')fail(409,'Приём предложений закрыт.');const existing:any=await db.prepare('SELECT owner,task FROM proposals WHERE id=?').bind(id).first();if(existing){if(existing.owner!==uid||existing.task!==taskId)fail(409,'Идентификатор предложения занят.');return response({ok:true,id,duplicate:true})}
const values=[id,taskId,uid,str(b.approach,10),str(b.experience??'',0),str(b.duration,2,120),str(b.price,2,120),str(b.contact,5,240),str(b.plan,10),safeLink(b.prototype),new Date().toISOString(),taskId];
const result=await db.prepare(`INSERT OR IGNORE INTO proposals(id,task,owner,approach,experience,duration,price,contact,plan,prototype,status,created) SELECT ?,?,?,?,?,?,?,?,?,?,'pending',? WHERE EXISTS(SELECT 1 FROM tasks WHERE id=? AND status='published')`).bind(...values).run();if(!result.meta.changes)fail(409,'Предложение уже обработано или приём закрыт.');return response({ok:true,id})}
if(b.action==='decide'){if(profile.role!=='business')fail(403,'Выбор доступен только бизнесу.');const taskId=str(b.task,1,80);const task:any=await db.prepare('SELECT * FROM tasks WHERE id=? AND owner=?').bind(taskId,uid).first();if(!task)fail(404,'Задача не найдена.');if(task.status!=='published')fail(409,'Решение уже принято или задача не опубликована.');if(!Array.isArray(b.selected)||b.selected.some((x:any)=>typeof x!=='string'))fail(400,'Некорректный список команд.');const ids=[...new Set<string>(b.selected)];const rows=await db.prepare('SELECT id FROM proposals WHERE task=?').bind(taskId).all();if(ids.some(id=>!rows.results.some(r=>r.id===id)))fail(400,'Выбрано предложение от другой задачи.');
// JSON membership avoids SQLite's bound-parameter limit for large selections.
await db.batch([db.prepare(`UPDATE proposals SET status=CASE WHEN id IN (SELECT value FROM json_each(?)) THEN 'selected' ELSE 'rejected' END WHERE task=? AND EXISTS(SELECT 1 FROM tasks WHERE id=? AND owner=? AND status='published')`).bind(JSON.stringify(ids),taskId,taskId,uid),db.prepare("UPDATE tasks SET status='closed' WHERE id=? AND owner=? AND status='published'").bind(taskId,uid)]);
return response({ok:true})}
if(b.action==='reportProgress'){const p:any=await db.prepare("SELECT * FROM proposals WHERE id=? AND owner=? AND status='selected'").bind(str(b.proposal,1,80),uid).first();if(!p)fail(403,'Отчёт может отправить только выбранная команда.');const r=await db.prepare("UPDATE proposals SET evidence=?,progress='submitted' WHERE id=? AND owner=? AND progress='none'").bind(str(b.evidence,10),p.id,uid).run();if(!r.meta.changes)fail(409,'Этап уже отправлен или подтверждён.');return response({ok:true})}
if(b.action==='confirmProgress'){const r=await db.prepare(`UPDATE proposals SET progress='approved',points=20 WHERE id=? AND status='selected' AND progress='submitted' AND EXISTS(SELECT 1 FROM tasks WHERE tasks.id=proposals.task AND tasks.owner=?)`).bind(str(b.proposal,1,80),uid).run();if(!r.meta.changes)fail(409,'Этап уже подтверждён либо недоступен для этого бизнеса.');return response({ok:true})}
fail(400,'Неизвестное действие.');})}

