import {writeFileSync,mkdirSync} from 'node:fs';
const common={title:'',category:'Аналитика',problem:'',need:'',users:'',result:'',metric:'',resources:'',constraints:'',contact:'',interaction:'',deadline:'',reward:'Учебный проект без оплаты',confirmed:1};
const cards=[
{...common,id:'demo-task-1',title:'Сократить списания выпечки',problem:'Пекарня каждый вечер списывает непроданную выпечку. Объём производства определяют на глаз.',need:'Прогнозировать спрос по дням недели.',users:'Управляющий и пекари смены',resources:'CSV с обезличенными продажами за 12 месяцев и остатками по дням.',result:'Прототип прогноза спроса и отчёт для управляющего.',metric:'Сократить списания минимум на 20% в пилоте.',constraints:'Пилот за 4 недели; без персональных данных; Python и CSV.',contact:'bakery@example.test',interaction:'Консультация 30 минут по вторникам. Управляющий проверяет промежуточный отчёт.'},
{...common,id:'demo-task-2',category:'Разработка',title:'Запись на пробное занятие',problem:'Администратор образовательного центра вручную собирает заявки из нескольких каналов и теряет часть обращений.',need:'Собрать заявки в одном кабинете.',users:'Родители учеников и администратор',resources:'Тестовое расписание и обезличенные примеры 20 заявок.',result:'Веб-форма записи и кабинет администратора.',metric:'Новая заявка появляется в кабинете за 5 секунд.',constraints:'Только тестовые данные; прототип за 3 недели.'},
{...common,id:'demo-task-3',category:'Исследования',title:'Разобраться с отказами в корзине',problem:'Клиенты мебельного магазина добавляют товар в корзину, но редко завершают заказ.',need:'Выявить причины отказа от заказа.',resources:'Обезличенная аналитика переходов и воронки за квартал.',result:'Отчёт о причинах отказа и список проверяемых улучшений.'},
{...common,id:'demo-task-4',category:'Маркетинг',title:'Найти аудиторию для новых курсов',problem:'У учебного центра снижается число заявок на курсы, а причины пока неизвестны.',need:'Определить подходящие каналы продвижения.',users:'Маркетолог учебного центра'},
{...common,id:'demo-task-5',category:'Дизайн',title:'Сделать понятнее наш сайт',problem:'Нужен удобный сайт.'}
];
const teams=[
['demo-team-1','Data Nomads','Аналитика и прогнозирование','Python, pandas, SQL','Retail, прогнозирование'],
['demo-team-2','Qadam Dev','Веб-разработка и интеграции','TypeScript, React, Node.js','Автоматизация процессов'],
['demo-team-3','Pixel Lab','UX-исследования и интерфейсы','Figma, HTML, CSS','Дизайн и образование'],
['demo-team-4','Insight Crew','Интервью и анализ данных','Python, Excel, Miro','Исследования пользователей'],
['demo-team-5','Growth Makers','Маркетинг и продуктовые эксперименты','SQL, аналитика, Figma','Маркетинг и рост']
].map(([id,name,skills,technologies,interests])=>({id,name,role:'team',skills,technologies,interests,university:'Демонстрационный университет'}));
const drafts=cards.map((t,i)=>({...common,id:'demo-draft-'+(i+1),title:['Нужен прогноз продаж','Теряем заявки','Клиенты бросают корзину','Мало студентов на курсах','Неудобный сайт'][i],category:t.category,problem:[t.problem,'Заявки приходят в разные каналы и теряются.','Клиенты часто уходят перед оплатой.','Не знаем, где искать слушателей.','Хотим улучшить наш сайт.'][i],resources:i===0?t.resources:'',confirmed:0}));
const proposals=teams.map((t,i)=>({id:'demo-proposal-'+(i+1),task:i<3?'demo-task-1':i===3?'demo-task-3':'demo-task-4',owner:t.id,approach:['Построим прогноз спроса с учётом дня недели.','Создадим простой кабинет загрузки и анализа продаж.','Исследуем рабочий процесс пекарей и спроектируем интерфейс.','Проведём интервью с пользователями и проверим причины отказа.','Проверим гипотезы продвижения курсов на тестовых данных.'][i],plan:'1. Уточнить требования. 2. Проверить данные. 3. Сделать прототип. 4. Показать результат бизнесу.',experience:'Учебный командный проект с анализом данных и презентацией результата.',duration:(i+2)+' недели',price:'Учебный проект без оплаты',contact:'team'+(i+1)+'@example.test',prototype:'https://example.com/prototype-'+(i+1),status:'pending'}));
export const demoData={notice:'Все записи синтетические. Ссылки на example.com — демонстрационные.',profiles:[{id:'demo-business',name:'Бизнес · Практика',role:'business',university:'',skills:'',interests:'',technologies:''},...teams],drafts,cards,proposals};
if(process.argv.includes('--write')){mkdirSync('data',{recursive:true});writeFileSync('data/demo.json',JSON.stringify(demoData,null,2)+'\n');console.log('Wrote 5 drafts, 5 cards, 5 teams and 5 proposals.')}
